---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: deploy/busybox
  name: deploy/busybox
spec:
  containers:
    - command:
        - sleep
        - "9999"
      image: busybox:1.31.1
      name: deploy/busybox
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
