apiVersion: v1
data:
    password: ENC[AES256_GCM,data:pUvgshErtrCCBAmb,iv:HjLdUyrWmfQGpveYF3pGcwcju+Pse99XpoHPrlb3L8U=,tag:26Z231B4sYqsGE1TbEFg3w==,type:str]
kind: Secret
metadata:
    name: redis-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-15T16:31:49Z'
    mac: ENC[AES256_GCM,data:cMGBrxZgj6lfepumQU3FkM9tJ5jsjV9gOeGLSgju9sEHYpCK4nsr3OegLnSehQhvB0+XMMCjghVFrSqLMKx7TKrHbcx3Pv8NjwMQlbMx+FrNfL6vXfKBz86poviXjXkxvbLUE1Vmz0LUSvVOwhncQT0bDVZfQUQ7+Fewb9HrTpk=,iv:lJZEf8HsvXGqbMBUeM8sktrvsl93zI5m1jtyrCmReVE=,tag:beoqz1wjSlF4X5JNxMvBNA==,type:str]
    pgp:
    -   created_at: '2020-11-15T16:31:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/At2/XuetZaAQv/TOItQI35WUaQ+NKuAsyYiCCQ0iBGsjvOLbmUK7c2618B
            tWPFB7gLADZj/2AboBhufbMkMaPsFJtdapEw7nub9LAzEkSKX7Up1T5YKgvd2MyY
            SgjOVMd58Dn9Nh/qOROF9bSZZrebA3k89ywwK5e86auoDoYKUpawbdbKjisyG9KT
            h/V8B5jyXFErnrKF0piNZivl7WpNOddnQV8cGeA2lqpFXIQFFEjzNOFeiRq2a6Oz
            0cFVeiRR3SzrGfHQXfY4qQpMN3/D12aGAkhESogTtoYZ7XJhSlvRN06K30aElQU0
            qVMDXqPj68BxNk5v/plVjTWj10fmnkLPgaDJtjXmR50FDHzlEUZT+5yRznyu2toC
            vTUpc1+HUlUvsnfHx6cQKEgPnV/XFAdDrk/KdmhqauvrTWg4Ax5GTBX6/Qd4riMH
            9lFcJDzplfEjaA2EuejXg5Wyu/bieZRF9ZAt0B62Mebo59HVBn8rakYh78TMG2nd
            wa98k2ONX6Im1um5xeEy0l4BIEi/7jFMFebJtwTFE0o2ki7aSwgoG2DMSEo9iYIG
            uukYM9ZVMdGVfQMYGeAXSWp8ut+LewXvpGMhTv8wGN1KFiRaTmHNgN0+MY6qQ4YY
            cp5RMngrKRqqAbe6lNxI
            =/8sH
            -----END PGP MESSAGE-----
        fp: 708C83D55218E8F274EA202F4CDE0BCBB6C2B5CB
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
